name    'intere-j2se'
version '0.0.1'
source 'https://github.com/intere/puppet-j2se.git'
author 'Eric Internicola'
license 'Apache 2.0'
summary 'Java 7 Installation (via wget & unpacking)'
description 'Downloads and unpacks Java for you'
project_page 'https://github.com/intere/puppet-j2se'
